var group__wellknownenums =
[
    [ "promeki::VideoPattern", "classpromeki_1_1VideoPattern.html", null ],
    [ "promeki::BurnPosition", "classpromeki_1_1BurnPosition.html", null ],
    [ "promeki::MediaIOOpenMode", "classpromeki_1_1MediaIOOpenMode.html", null ],
    [ "promeki::AudioPattern", "classpromeki_1_1AudioPattern.html", null ],
    [ "promeki::AudioMarkerType", "classpromeki_1_1AudioMarkerType.html", null ],
    [ "promeki::ChromaSubsampling", "classpromeki_1_1ChromaSubsampling.html", null ],
    [ "promeki::AudioDataType", "classpromeki_1_1AudioDataType.html", null ],
    [ "promeki::CscPath", "classpromeki_1_1CscPath.html", null ],
    [ "promeki::QuickTimeLayout", "classpromeki_1_1QuickTimeLayout.html", null ],
    [ "promeki::RtpPacingMode", "classpromeki_1_1RtpPacingMode.html", null ],
    [ "promeki::MetadataRtpFormat", "classpromeki_1_1MetadataRtpFormat.html", null ],
    [ "promeki::ByteCountStyle", "classpromeki_1_1ByteCountStyle.html", null ],
    [ "promeki::ImgSeqPathMode", "classpromeki_1_1ImgSeqPathMode.html", null ],
    [ "promeki::TimecodePackFormat", "classpromeki_1_1TimecodePackFormat.html", null ],
    [ "promeki::VideoScanMode", "classpromeki_1_1VideoScanMode.html", [
      [ "isInterlaced", "classpromeki_1_1VideoScanMode.html#ac2b6ecf332e577baa26bdf77583829a0", null ]
    ] ],
    [ "promeki::MediaIODirection", "classpromeki_1_1MediaIODirection.html", null ],
    [ "promeki::MediaPayloadKind", "classpromeki_1_1MediaPayloadKind.html", null ],
    [ "promeki::FrameType", "classpromeki_1_1FrameType.html", null ],
    [ "promeki::AudioSourceHint", "classpromeki_1_1AudioSourceHint.html", null ],
    [ "promeki::V4l2PowerLineMode", "classpromeki_1_1V4l2PowerLineMode.html", null ],
    [ "promeki::V4l2ExposureMode", "classpromeki_1_1V4l2ExposureMode.html", null ],
    [ "promeki::SrcQuality", "classpromeki_1_1SrcQuality.html", null ],
    [ "promeki::ClockEpoch", "classpromeki_1_1ClockEpoch.html", null ],
    [ "promeki::EUI64Format", "classpromeki_1_1EUI64Format.html", null ],
    [ "promeki::InspectorTest", "classpromeki_1_1InspectorTest.html", null ],
    [ "promeki::RateControlMode", "classpromeki_1_1RateControlMode.html", null ],
    [ "promeki::VideoEncoderPreset", "classpromeki_1_1VideoEncoderPreset.html", null ],
    [ "promeki::OpusApplication", "classpromeki_1_1OpusApplication.html", null ],
    [ "promeki::VideoRange", "classpromeki_1_1VideoRange.html", null ],
    [ "promeki::ColorPrimaries", "classpromeki_1_1ColorPrimaries.html", null ],
    [ "promeki::TransferCharacteristics", "classpromeki_1_1TransferCharacteristics.html", null ],
    [ "promeki::MatrixCoefficients", "classpromeki_1_1MatrixCoefficients.html", null ],
    [ "promeki::NullPacingMode", "classpromeki_1_1NullPacingMode.html", null ],
    [ "promeki::ChannelRole", "classpromeki_1_1ChannelRole.html", null ],
    [ "promeki::NdiBandwidth", "classpromeki_1_1NdiBandwidth.html", null ],
    [ "promeki::NdiColorFormat", "classpromeki_1_1NdiColorFormat.html", null ],
    [ "promeki::NdiReceiveBitDepth", "classpromeki_1_1NdiReceiveBitDepth.html", null ],
    [ "promeki::TransferCharacteristics::ARIB_STD_B67", "group__wellknownenums.html#gab933cb36d1dc82eb0f22d990eb555a10", null ],
    [ "promeki::ByteCountStyle::Binary", "group__wellknownenums.html#ga021546c6a33b935c31aa1dbf479043c4", null ],
    [ "promeki::ByteCountStyle::Metric", "group__wellknownenums.html#gad07544583422ae64ac64d6dccff788ae", null ],
    [ "promeki::TransferCharacteristics::SMPTE2084", "group__wellknownenums.html#ga3502e40e1059ea48054894e5ee29b8d5", null ]
];