var group__wellknownenums =
[
    [ "VideoPattern", "classVideoPattern.html", null ],
    [ "BurnPosition", "classBurnPosition.html", null ],
    [ "AudioPattern", "classAudioPattern.html", null ],
    [ "ChromaSubsampling", "classChromaSubsampling.html", null ],
    [ "AudioDataType", "classAudioDataType.html", null ],
    [ "CscPath", "classCscPath.html", null ],
    [ "QuickTimeLayout", "classQuickTimeLayout.html", null ],
    [ "RtpPacingMode", "classRtpPacingMode.html", null ],
    [ "MetadataRtpFormat", "classMetadataRtpFormat.html", null ],
    [ "ByteCountStyle", "classByteCountStyle.html", null ],
    [ "ImgSeqPathMode", "classImgSeqPathMode.html", null ],
    [ "TimecodePackFormat", "classTimecodePackFormat.html", null ],
    [ "InterlaceMode", "classInterlaceMode.html", null ],
    [ "MediaIODirection", "classMediaIODirection.html", null ],
    [ "AudioSourceHint", "classAudioSourceHint.html", null ],
    [ "V4l2PowerLineMode", "classV4l2PowerLineMode.html", null ],
    [ "V4l2ExposureMode", "classV4l2ExposureMode.html", null ],
    [ "SrcQuality", "classSrcQuality.html", null ],
    [ "ClockEpoch", "classClockEpoch.html", null ],
    [ "EUI64Format", "classEUI64Format.html", null ],
    [ "InspectorTest", "classInspectorTest.html", null ],
    [ "VideoRateControl", "classVideoRateControl.html", null ],
    [ "VideoEncoderPreset", "classVideoEncoderPreset.html", null ],
    [ "ByteCountStyle::Binary", "group__wellknownenums.html#ga9d2d3b34e2e3e410560df0546f7dc983", null ],
    [ "ByteCountStyle::Metric", "group__wellknownenums.html#ga6d3dd14d60f115203c9061ab83edb892", null ]
];