var hierarchy =
[
    [ "Application", "classApplication.html", [
      [ "TuiApplication", "classTuiApplication.html", null ]
    ] ],
    [ "Array< T, NumValues >", "classArray.html", null ],
    [ "Array< double, 2 >", "classArray.html", null ],
    [ "Array< double, 3 >", "classArray.html", null ],
    [ "Array< int32_t, NumValues >", "classArray.html", null ],
    [ "Array< RowDataType, H >", "classArray.html", null ],
    [ "Array< String, NumNotes >", "classArray.html", null ],
    [ "Array< uint8_t, 16 >", "classArray.html", null ],
    [ "Audio", "classAudio.html", null ],
    [ "AudioDesc", "classAudioDesc.html", null ],
    [ "AudioFile", "classAudioFile.html", null ],
    [ "AudioFileFactory", "classAudioFileFactory.html", null ],
    [ "AudioGen", "classAudioGen.html", null ],
    [ "MemPool::Block", "classMemPool_1_1Block.html", null ],
    [ "Buffer", "classBuffer.html", null ],
    [ "BuildInfo", "structBuildInfo.html", null ],
    [ "ByteArray< NumBytes >", "classByteArray.html", null ],
    [ "Char", "classChar.html", null ],
    [ "String::CharIterator", "classString_1_1CharIterator.html", null ],
    [ "CIEPoint", "classCIEPoint.html", null ],
    [ "CIEWavelength", "structCIEWavelength.html", null ],
    [ "CmdLineParser", "classCmdLineParser.html", null ],
    [ "Codec", "classCodec.html", null ],
    [ "Color", "classColor.html", null ],
    [ "ColorSpace", "classColorSpace.html", null ],
    [ "PixelFormat::CompDesc", "structPixelFormat_1_1CompDesc.html", null ],
    [ "CompiledCodepoints< Count >", "classCompiledCodepoints.html", null ],
    [ "CompiledString< N >", "classCompiledString.html", null ],
    [ "AudioBlock::Config", "classAudioBlock_1_1Config.html", null ],
    [ "AudioGen::Config", "structAudioGen_1_1Config.html", null ],
    [ "CSC", "structCSC.html", null ],
    [ "ColorSpace::Data", "structColorSpace_1_1Data.html", null ],
    [ "PixelFormat::Data", "structPixelFormat_1_1Data.html", null ],
    [ "DateTime", "classDateTime.html", null ],
    [ "Error", "classError.html", null ],
    [ "Event", "classEvent.html", [
      [ "KeyEvent", "classKeyEvent.html", null ],
      [ "MouseEvent", "classMouseEvent.html", null ],
      [ "TimerEvent", "classTimerEvent.html", null ],
      [ "TuiPaintEvent", "classTuiPaintEvent.html", null ],
      [ "TuiResizeEvent", "classTuiResizeEvent.html", null ]
    ] ],
    [ "EventLoop", "classEventLoop.html", null ],
    [ "std::false_type", null, [
      [ "IsSharedObject< T, typename >", "structIsSharedObject.html", null ]
    ] ],
    [ "File", "classFile.html", null ],
    [ "FileInfo", "classFileInfo.html", null ],
    [ "FontPainter", "classFontPainter.html", null ],
    [ "AudioDesc::Format", "structAudioDesc_1_1Format.html", null ],
    [ "FourCC", "classFourCC.html", null ],
    [ "Frame", "classFrame.html", null ],
    [ "FrameRate", "classFrameRate.html", null ],
    [ "std::hash< promeki::String >", "structstd_1_1hash_3_01promeki_1_1String_01_4.html", null ],
    [ "Image", "classImage.html", null ],
    [ "ImageDesc", "classImageDesc.html", null ],
    [ "ImageFile", "classImageFile.html", null ],
    [ "ImageFileIO", "classImageFileIO.html", null ],
    [ "AudioFile::Impl", "classAudioFile_1_1Impl.html", null ],
    [ "PaintEngine::Impl", "classPaintEngine_1_1Impl.html", null ],
    [ "Codec::Instance", "classCodec_1_1Instance.html", null ],
    [ "JsonArray", "classJsonArray.html", null ],
    [ "JsonObject", "classJsonObject.html", null ],
    [ "Line< T, N >", "classLine.html", null ],
    [ "List< T >", "classList.html", null ],
    [ "List< AudioDesc >", "classList.html", null ],
    [ "List< AudioGen::Config >", "classList.html", null ],
    [ "List< Char >", "classList.html", null ],
    [ "List< Cleanup >", "classList.html", null ],
    [ "List< CmdLineParser::Option >", "classList.html", null ],
    [ "List< FourCC >", "classList.html", null ],
    [ "List< GridItem >", "classList.html", null ],
    [ "List< ImageDesc >", "classList.html", null ],
    [ "List< Info >", "classList.html", null ],
    [ "List< int >", "classList.html", null ],
    [ "List< Item >", "classList.html", null ],
    [ "List< ObjectBase * >", "classList.html", null ],
    [ "List< Params >", "classList.html", null ],
    [ "List< PixelFormat::CompDesc >", "classList.html", null ],
    [ "List< PixelFormat::PlaneDesc >", "classList.html", null ],
    [ "List< SignalMeta * >", "classList.html", null ],
    [ "List< SlotItem >", "classList.html", null ],
    [ "List< SlotMeta * >", "classList.html", null ],
    [ "List< String >", "classList.html", [
      [ "StringList", "classStringList.html", null ]
    ] ],
    [ "List< Tab >", "classList.html", null ],
    [ "List< TabPos >", "classList.html", null ],
    [ "List< TimerInfo >", "classList.html", null ],
    [ "List< TuiAction * >", "classList.html", null ],
    [ "List< TuiCell >", "classList.html", null ],
    [ "List< TuiLayout * >", "classList.html", null ],
    [ "List< TuiMenu * >", "classList.html", null ],
    [ "List< TuiWidget * >", "classList.html", null ],
    [ "Logger::LogEntry", "structLogger_1_1LogEntry.html", null ],
    [ "Logger::LogFormat", "structLogger_1_1LogFormat.html", null ],
    [ "Logger", "classLogger.html", null ],
    [ "Map< K, V >", "classMap.html", null ],
    [ "Map< ID, VariantImpl >", "classMap.html", null ],
    [ "Map< int, int >", "classMap.html", null ],
    [ "Map< ObjectBasePtr *, ObjectBasePtr * >", "classMap.html", null ],
    [ "Map< String, CmdLineParser::Option >", "classMap.html", null ],
    [ "Map< String, Params >", "classMap.html", null ],
    [ "Map< uintptr_t, Block >", "classMap.html", null ],
    [ "Matrix< T, W, H >", "classMatrix.html", null ],
    [ "Matrix3x3", "classMatrix3x3.html", null ],
    [ "MemAllocation", "structMemAllocation.html", null ],
    [ "MemPool", "classMemPool.html", null ],
    [ "MemSpace", "classMemSpace.html", null ],
    [ "Metadata", "classMetadata.html", null ],
    [ "ObjectBase::MetaInfo", "classObjectBase_1_1MetaInfo.html", null ],
    [ "MidiNote", "classMidiNote.html", null ],
    [ "MidiNoteNames", "classMidiNoteNames.html", null ],
    [ "Timecode::Mode", "classTimecode_1_1Mode.html", null ],
    [ "MusicalNote", "classMusicalNote.html", null ],
    [ "MusicalScale", "classMusicalScale.html", null ],
    [ "NoteSequenceParser", "classNoteSequenceParser.html", null ],
    [ "NumName", "classNumName.html", null ],
    [ "NumNameSeq", "classNumNameSeq.html", null ],
    [ "ObfuscatedString< N, Seed >", "classObfuscatedString.html", null ],
    [ "ObjectBase", "classObjectBase.html", [
      [ "AudioBlock", "classAudioBlock.html", null ],
      [ "Thread", "classThread.html", null ],
      [ "TuiAction", "classTuiAction.html", null ],
      [ "TuiLayout", "classTuiLayout.html", [
        [ "TuiBoxLayout", "classTuiBoxLayout.html", [
          [ "TuiHBoxLayout", "classTuiHBoxLayout.html", null ],
          [ "TuiVBoxLayout", "classTuiVBoxLayout.html", null ]
        ] ],
        [ "TuiGridLayout", "classTuiGridLayout.html", null ]
      ] ],
      [ "TuiWidget", "classTuiWidget.html", [
        [ "TuiButton", "classTuiButton.html", null ],
        [ "TuiCheckBox", "classTuiCheckBox.html", null ],
        [ "TuiFrame", "classTuiFrame.html", null ],
        [ "TuiLabel", "classTuiLabel.html", null ],
        [ "TuiLineEdit", "classTuiLineEdit.html", null ],
        [ "TuiListView", "classTuiListView.html", null ],
        [ "TuiMenu", "classTuiMenu.html", null ],
        [ "TuiMenuBar", "classTuiMenuBar.html", null ],
        [ "TuiProgressBar", "classTuiProgressBar.html", null ],
        [ "TuiScrollArea", "classTuiScrollArea.html", null ],
        [ "TuiSplitter", "classTuiSplitter.html", null ],
        [ "TuiStatusBar", "classTuiStatusBar.html", null ],
        [ "TuiTabWidget", "classTuiTabWidget.html", null ],
        [ "TuiTextArea", "classTuiTextArea.html", null ]
      ] ]
    ] ],
    [ "ObjectBasePtr", "classObjectBasePtr.html", null ],
    [ "MemSpace::Ops", "structMemSpace_1_1Ops.html", null ],
    [ "CmdLineParser::Option", "classCmdLineParser_1_1Option.html", null ],
    [ "std::ostream", null, [
      [ "AnsiStream", "classAnsiStream.html", null ]
    ] ],
    [ "PaintEngine", "classPaintEngine.html", null ],
    [ "TuiInputParser::ParsedEvent", "structTuiInputParser_1_1ParsedEvent.html", null ],
    [ "PIDController< ValueType, TimeType >", "classPIDController.html", null ],
    [ "PixelFormat", "classPixelFormat.html", null ],
    [ "PixelFormat::PlaneDesc", "structPixelFormat_1_1PlaneDesc.html", null ],
    [ "Point< T, NumValues >", "classPoint.html", null ],
    [ "Point< int32_t, 2 >", "classPoint.html", null ],
    [ "Point< T, 2 >", "classPoint.html", null ],
    [ "Point< T, N >", "classPoint.html", null ],
    [ "Queue< T >", "classQueue.html", null ],
    [ "Queue< Command >", "classQueue.html", null ],
    [ "Queue< Item >", "classQueue.html", null ],
    [ "Rational< T >", "classRational.html", null ],
    [ "Rational< unsigned int >", "classRational.html", null ],
    [ "Rect< T >", "classRect.html", null ],
    [ "Rect< int32_t >", "classRect.html", null ],
    [ "RefCount", "classRefCount.html", null ],
    [ "RegEx", "classRegEx.html", null ],
    [ "Signal< Args >::removeConstAndRef< T >", "structSignal_1_1removeConstAndRef.html", null ],
    [ "Slot< Args >::removeConstAndRef< T >", "structSlot_1_1removeConstAndRef.html", null ],
    [ "Set< T >", "classSet.html", null ],
    [ "Set< Block >", "classSet.html", null ],
    [ "SharedPtr< T, CopyOnWrite, ST >", "classSharedPtr.html", null ],
    [ "SharedPtr< AudioFile::Impl >", "classSharedPtr.html", null ],
    [ "SharedPtr< Buffer >", "classSharedPtr.html", null ],
    [ "SharedPtr< PaintEngine::Impl, false >", "classSharedPtr.html", null ],
    [ "SharedPtr< StringData >", "classSharedPtr.html", null ],
    [ "SharedPtrProxy< T >", "classSharedPtrProxy.html", null ],
    [ "Signal< Args >", "classSignal.html", null ],
    [ "Signal< ObjectBase * >", "classSignal.html", null ],
    [ "ObjectBase::SignalMeta", "classObjectBase_1_1SignalMeta.html", null ],
    [ "Size2DTemplate< T >", "classSize2DTemplate.html", null ],
    [ "Size2DTemplate< int32_t >", "classSize2DTemplate.html", null ],
    [ "Size2DTemplate< uint32_t >", "classSize2DTemplate.html", null ],
    [ "Slot< Args >", "classSlot.html", null ],
    [ "ObjectBase::SlotMeta", "classObjectBase_1_1SlotMeta.html", null ],
    [ "MemPool::Stats", "structMemPool_1_1Stats.html", null ],
    [ "std::streambuf", null, [
      [ "StreamString", "classStreamString.html", null ]
    ] ],
    [ "String", "classString.html", null ],
    [ "StringData", "classStringData.html", [
      [ "StringLatin1Data", "classStringLatin1Data.html", null ],
      [ "StringLiteralData", "classStringLiteralData.html", null ],
      [ "StringUnicodeData", "classStringUnicodeData.html", null ],
      [ "StringUnicodeLiteralData", "classStringUnicodeLiteralData.html", null ]
    ] ],
    [ "StructDatabase< KeyType, StructType >", "classStructDatabase.html", null ],
    [ "System", "classSystem.html", null ],
    [ "Terminal", "classTerminal.html", null ],
    [ "Timecode", "classTimecode.html", null ],
    [ "TimeStamp", "classTimeStamp.html", null ],
    [ "std::true_type", null, [
      [ "IsSharedObject< T, std::void_t< decltype(&T::_promeki_refct)> >", "structIsSharedObject_3_01T_00_01std_1_1void__t_3_01decltype_07_6T_1_1__promeki__refct_08_4_01_4.html", null ]
    ] ],
    [ "TuiCell", "structTuiCell.html", null ],
    [ "TuiInputParser", "classTuiInputParser.html", null ],
    [ "TuiPainter", "classTuiPainter.html", null ],
    [ "TuiPalette", "classTuiPalette.html", null ],
    [ "TuiScreen", "classTuiScreen.html", null ],
    [ "TuiStyle", "classTuiStyle.html", null ],
    [ "TuiStyleState", "classTuiStyleState.html", null ],
    [ "UUID", "classUUID.html", null ],
    [ "detail::VariantEnd", "structdetail_1_1VariantEnd.html", null ],
    [ "VariantImpl< Types >", "classVariantImpl.html", null ],
    [ "VideoDesc", "classVideoDesc.html", null ],
    [ "XYZColor", "classXYZColor.html", null ]
];