var hierarchy =
[
    [ "AnsiStream", "classAnsiStream.html", null ],
    [ "Application", "classApplication.html", null ],
    [ "Array< T, NumValues >", "classArray.html", null ],
    [ "Array< CIEPoint, 4 >", "classArray.html", null ],
    [ "Array< double, 2 >", "classArray.html", null ],
    [ "Array< double, 3 >", "classArray.html", null ],
    [ "Array< int32_t, NumValues >", "classArray.html", null ],
    [ "Array< PlaneInfo, MaxPlanes >", "classArray.html", null ],
    [ "Array< RowDataType, H >", "classArray.html", null ],
    [ "Array< String, NumNotes >", "classArray.html", null ],
    [ "Array< uint8_t, 16 >", "classArray.html", null ],
    [ "Array< uint8_t, 6 >", "classArray.html", null ],
    [ "Array< uint8_t, 8 >", "classArray.html", null ],
    [ "Array< uint8_t, ExtendedSize >", "classArray.html", null ],
    [ "Atomic< T >", "classAtomic.html", null ],
    [ "Atomic< bool >", "classAtomic.html", null ],
    [ "Atomic< int >", "classAtomic.html", null ],
    [ "Atomic< int64_t >", "classAtomic.html", null ],
    [ "Atomic< std::thread::id >", "classAtomic.html", null ],
    [ "Atomic< uint64_t >", "classAtomic.html", null ],
    [ "Audio", "classAudio.html", null ],
    [ "AudioBuffer", "classAudioBuffer.html", null ],
    [ "AudioCodec", "classAudioCodec.html", null ],
    [ "AudioDesc", "classAudioDesc.html", null ],
    [ "AudioFile", "classAudioFile.html", null ],
    [ "AudioGen", "classAudioGen.html", null ],
    [ "AudioLevel", "classAudioLevel.html", null ],
    [ "AudioResampler", "classAudioResampler.html", null ],
    [ "AudioTestPattern", "classAudioTestPattern.html", null ],
    [ "AvcDecoderConfig", "structAvcDecoderConfig.html", null ],
    [ "ImageDataDecoder::Band", "structImageDataDecoder_1_1Band.html", null ],
    [ "Benchmark", "classBenchmark.html", null ],
    [ "BenchmarkCase", "classBenchmarkCase.html", null ],
    [ "BenchmarkReporter", "classBenchmarkReporter.html", null ],
    [ "BenchmarkResult", "classBenchmarkResult.html", null ],
    [ "BenchmarkRunner", "classBenchmarkRunner.html", null ],
    [ "BenchmarkState", "classBenchmarkState.html", null ],
    [ "MemPool::Block", "classMemPool_1_1Block.html", null ],
    [ "Buffer", "classBuffer.html", null ],
    [ "BufferPool", "classBufferPool.html", null ],
    [ "BufferView", "classBufferView.html", [
      [ "RtpPacket", "classRtpPacket.html", null ]
    ] ],
    [ "BuildInfo", "structBuildInfo.html", null ],
    [ "ByteArray< NumBytes >", "classByteArray.html", null ],
    [ "Char", "classChar.html", null ],
    [ "String::CharIterator", "classString_1_1CharIterator.html", null ],
    [ "CIEPoint", "classCIEPoint.html", null ],
    [ "CIEWavelength", "structCIEWavelength.html", null ],
    [ "Clock", "classClock.html", [
      [ "SDLAudioClock", "classSDLAudioClock.html", null ],
      [ "SyntheticClock", "classSyntheticClock.html", null ],
      [ "WallClock", "classWallClock.html", null ]
    ] ],
    [ "ClockDomain", "classClockDomain.html", null ],
    [ "ClockJitter", "structClockJitter.html", null ],
    [ "CmdLineParser", "classCmdLineParser.html", null ],
    [ "Color", "classColor.html", null ],
    [ "ColorModel", "classColorModel.html", null ],
    [ "PixelFormat::CompDesc", "structPixelFormat_1_1CompDesc.html", null ],
    [ "CompiledCodepoints< Count >", "classCompiledCodepoints.html", null ],
    [ "CompiledString< N >", "classCompiledString.html", null ],
    [ "ColorModel::CompInfo", "structColorModel_1_1CompInfo.html", null ],
    [ "PixelDesc::CompSemantic", "structPixelDesc_1_1CompSemantic.html", null ],
    [ "AudioBlock::Config", "classAudioBlock_1_1Config.html", null ],
    [ "AudioGen::Config", "structAudioGen_1_1Config.html", null ],
    [ "FrameBridge::Config", "structFrameBridge_1_1Config.html", null ],
    [ "ContentLightLevel", "classContentLightLevel.html", null ],
    [ "FileFormatFactory< Product >::Context", "structFileFormatFactory_1_1Context.html", null ],
    [ "CrashHandler", "classCrashHandler.html", null ],
    [ "CRC< T >", "classCRC.html", null ],
    [ "CSCContext", "classCSCContext.html", null ],
    [ "CSCPipeline", "classCSCPipeline.html", null ],
    [ "CSCRegistry", "classCSCRegistry.html", null ],
    [ "CudaBootstrap", "classCudaBootstrap.html", null ],
    [ "CudaDevice", "classCudaDevice.html", null ],
    [ "AudioCodec::Data", "structAudioCodec_1_1Data.html", null ],
    [ "ColorModel::Data", "structColorModel_1_1Data.html", null ],
    [ "PixelDesc::Data", "structPixelDesc_1_1Data.html", null ],
    [ "PixelFormat::Data", "structPixelFormat_1_1Data.html", null ],
    [ "VideoCodec::Data", "structVideoCodec_1_1Data.html", null ],
    [ "PacketTransport::Datagram", "structPacketTransport_1_1Datagram.html", null ],
    [ "UdpSocket::Datagram", "structUdpSocket_1_1Datagram.html", null ],
    [ "DataStream", "classDataStream.html", null ],
    [ "DateTime", "classDateTime.html", null ],
    [ "ImageDataDecoder::DecodedItem", "structImageDataDecoder_1_1DecodedItem.html", null ],
    [ "LtcDecoder::DecodedTimecode", "structLtcDecoder_1_1DecodedTimecode.html", null ],
    [ "Enum::Definition", "structEnum_1_1Definition.html", null ],
    [ "Deque< T >", "classDeque.html", null ],
    [ "Dir", "classDir.html", null ],
    [ "Duration", "classDuration.html", null ],
    [ "ElapsedTimer", "classElapsedTimer.html", null ],
    [ "EncodedDesc", "classEncodedDesc.html", null ],
    [ "Benchmark::Entry", "structBenchmark_1_1Entry.html", null ],
    [ "Enum::Entry", "structEnum_1_1Entry.html", null ],
    [ "Enum", "classEnum.html", [
      [ "TypedEnum< AudioDataType >", "classTypedEnum.html", [
        [ "AudioDataType", "classAudioDataType.html", null ]
      ] ],
      [ "TypedEnum< AudioPattern >", "classTypedEnum.html", [
        [ "AudioPattern", "classAudioPattern.html", null ]
      ] ],
      [ "TypedEnum< AudioSourceHint >", "classTypedEnum.html", [
        [ "AudioSourceHint", "classAudioSourceHint.html", null ]
      ] ],
      [ "TypedEnum< BurnPosition >", "classTypedEnum.html", [
        [ "BurnPosition", "classBurnPosition.html", null ]
      ] ],
      [ "TypedEnum< ByteCountStyle >", "classTypedEnum.html", [
        [ "ByteCountStyle", "classByteCountStyle.html", null ]
      ] ],
      [ "TypedEnum< ChromaSubsampling >", "classTypedEnum.html", [
        [ "ChromaSubsampling", "classChromaSubsampling.html", null ]
      ] ],
      [ "TypedEnum< ClockEpoch >", "classTypedEnum.html", [
        [ "ClockEpoch", "classClockEpoch.html", null ]
      ] ],
      [ "TypedEnum< ColorPrimaries >", "classTypedEnum.html", [
        [ "ColorPrimaries", "classColorPrimaries.html", null ]
      ] ],
      [ "TypedEnum< CscPath >", "classTypedEnum.html", [
        [ "CscPath", "classCscPath.html", null ]
      ] ],
      [ "TypedEnum< EUI64Format >", "classTypedEnum.html", [
        [ "EUI64Format", "classEUI64Format.html", null ]
      ] ],
      [ "TypedEnum< ImgSeqPathMode >", "classTypedEnum.html", [
        [ "ImgSeqPathMode", "classImgSeqPathMode.html", null ]
      ] ],
      [ "TypedEnum< InspectorTest >", "classTypedEnum.html", [
        [ "InspectorTest", "classInspectorTest.html", null ]
      ] ],
      [ "TypedEnum< MatrixCoefficients >", "classTypedEnum.html", [
        [ "MatrixCoefficients", "classMatrixCoefficients.html", null ]
      ] ],
      [ "TypedEnum< MediaIODirection >", "classTypedEnum.html", [
        [ "MediaIODirection", "classMediaIODirection.html", null ]
      ] ],
      [ "TypedEnum< MetadataRtpFormat >", "classTypedEnum.html", [
        [ "MetadataRtpFormat", "classMetadataRtpFormat.html", null ]
      ] ],
      [ "TypedEnum< QuickTimeLayout >", "classTypedEnum.html", [
        [ "QuickTimeLayout", "classQuickTimeLayout.html", null ]
      ] ],
      [ "TypedEnum< RtpPacingMode >", "classTypedEnum.html", [
        [ "RtpPacingMode", "classRtpPacingMode.html", null ]
      ] ],
      [ "TypedEnum< SrcQuality >", "classTypedEnum.html", [
        [ "SrcQuality", "classSrcQuality.html", null ]
      ] ],
      [ "TypedEnum< TimecodePackFormat >", "classTypedEnum.html", [
        [ "TimecodePackFormat", "classTimecodePackFormat.html", null ]
      ] ],
      [ "TypedEnum< TransferCharacteristics >", "classTypedEnum.html", [
        [ "TransferCharacteristics", "classTransferCharacteristics.html", null ]
      ] ],
      [ "TypedEnum< V4l2ExposureMode >", "classTypedEnum.html", [
        [ "V4l2ExposureMode", "classV4l2ExposureMode.html", null ]
      ] ],
      [ "TypedEnum< V4l2PowerLineMode >", "classTypedEnum.html", [
        [ "V4l2PowerLineMode", "classV4l2PowerLineMode.html", null ]
      ] ],
      [ "TypedEnum< VideoEncoderPreset >", "classTypedEnum.html", [
        [ "VideoEncoderPreset", "classVideoEncoderPreset.html", null ]
      ] ],
      [ "TypedEnum< VideoPattern >", "classTypedEnum.html", [
        [ "VideoPattern", "classVideoPattern.html", null ]
      ] ],
      [ "TypedEnum< VideoRange >", "classTypedEnum.html", [
        [ "VideoRange", "classVideoRange.html", null ]
      ] ],
      [ "TypedEnum< VideoRateControl >", "classTypedEnum.html", [
        [ "VideoRateControl", "classVideoRateControl.html", null ]
      ] ],
      [ "TypedEnum< VideoScanMode >", "classTypedEnum.html", [
        [ "VideoScanMode", "classVideoScanMode.html", null ]
      ] ],
      [ "TypedEnum< Derived >", "classTypedEnum.html", null ]
    ] ],
    [ "EnumList", "classEnumList.html", null ],
    [ "Env", "classEnv.html", null ],
    [ "Error", "classError.html", null ],
    [ "EUI64", "classEUI64.html", null ],
    [ "Event", "classEvent.html", [
      [ "KeyEvent", "classKeyEvent.html", null ],
      [ "MouseEvent", "classMouseEvent.html", null ],
      [ "PaintEvent", "classPaintEvent.html", null ],
      [ "ResizeEvent", "classResizeEvent.html", null ],
      [ "TimerEvent", "classTimerEvent.html", null ]
    ] ],
    [ "EventLoop", "classEventLoop.html", null ],
    [ "std::false_type", null, [
      [ "IsSharedObject< T, typename >", "structIsSharedObject.html", null ],
      [ "detail::is_type_registry< T >", "structdetail_1_1is__type__registry.html", null ]
    ] ],
    [ "FileFormatFactory< Product >", "classFileFormatFactory.html", null ],
    [ "FileInfo", "classFileInfo.html", null ],
    [ "FilePath", "classFilePath.html", null ],
    [ "Font", "classFont.html", [
      [ "BasicFont", "classBasicFont.html", null ],
      [ "FastFont", "classFastFont.html", null ]
    ] ],
    [ "AudioDesc::Format", "structAudioDesc_1_1Format.html", null ],
    [ "MediaIO::FormatDesc", "structMediaIO_1_1FormatDesc.html", null ],
    [ "std::formatter", null, [
      [ "ToStringFormatter< T >", "structToStringFormatter.html", null ],
      [ "std::formatter< promeki::Char >", "structstd_1_1formatter_3_01promeki_1_1Char_01_4.html", null ],
      [ "std::formatter< promeki::String >", "structstd_1_1formatter_3_01promeki_1_1String_01_4.html", null ],
      [ "std::formatter< promeki::Variant >", "structstd_1_1formatter_3_01promeki_1_1Variant_01_4.html", null ],
      [ "std::formatter< promeki::VariantImpl< Types... > >", "structstd_1_1formatter_3_01promeki_1_1VariantImpl_3_01Types_8_8_8_01_4_01_4.html", null ]
    ] ],
    [ "std::formatter< promeki::Duration >", "structstd_1_1formatter_3_01promeki_1_1Duration_01_4.html", null ],
    [ "std::formatter< promeki::EUI64 >", "structstd_1_1formatter_3_01promeki_1_1EUI64_01_4.html", null ],
    [ "std::formatter< promeki::Timecode >", "structstd_1_1formatter_3_01promeki_1_1Timecode_01_4.html", null ],
    [ "std::formatter< promeki::VideoFormat >", "structstd_1_1formatter_3_01promeki_1_1VideoFormat_01_4.html", null ],
    [ "FourCC", "classFourCC.html", null ],
    [ "Frame", "classFrame.html", null ],
    [ "DebugMediaFile::FrameIndexEntry", "structDebugMediaFile_1_1FrameIndexEntry.html", null ],
    [ "FramePacer", "classFramePacer.html", null ],
    [ "FrameRate", "classFrameRate.html", null ],
    [ "FrameSync", "classFrameSync.html", null ],
    [ "Future< T >", "classFuture.html", null ],
    [ "Future< void >", "classFuture_3_01void_01_4.html", null ],
    [ "MulticastReceiver::GroupEntry", "structMulticastReceiver_1_1GroupEntry.html", null ],
    [ "H264Bitstream", "classH264Bitstream.html", null ],
    [ "ColorModel::H273", "structColorModel_1_1H273.html", null ],
    [ "HashMap< K, V >", "classHashMap.html", null ],
    [ "HashSet< T >", "classHashSet.html", null ],
    [ "HevcDecoderConfig", "structHevcDecoderConfig.html", null ],
    [ "Histogram", "classHistogram.html", null ],
    [ "Image", "classImage.html", null ],
    [ "ImageCodec", "classImageCodec.html", [
      [ "JpegImageCodec", "classJpegImageCodec.html", null ],
      [ "JpegXsImageCodec", "classJpegXsImageCodec.html", null ]
    ] ],
    [ "ImageDataDecoder", "classImageDataDecoder.html", null ],
    [ "ImageDataEncoder", "classImageDataEncoder.html", null ],
    [ "ImageDesc", "classImageDesc.html", null ],
    [ "ImageFile", "classImageFile.html", null ],
    [ "ImageFileIO", "classImageFileIO.html", null ],
    [ "ImgSeq", "classImgSeq.html", null ],
    [ "AudioFile::Impl", "classAudioFile_1_1Impl.html", null ],
    [ "PaintEngine::Impl", "classPaintEngine_1_1Impl.html", null ],
    [ "QuickTime::Impl", "classQuickTime_1_1Impl.html", null ],
    [ "InspectorDiscontinuity", "structInspectorDiscontinuity.html", null ],
    [ "InspectorEvent", "structInspectorEvent.html", null ],
    [ "InspectorSnapshot", "structInspectorSnapshot.html", null ],
    [ "File::IOVec", "structFile_1_1IOVec.html", null ],
    [ "Ipv4Address", "classIpv4Address.html", null ],
    [ "Ipv6Address", "classIpv6Address.html", null ],
    [ "ImageDataEncoder::Item", "structImageDataEncoder_1_1Item.html", null ],
    [ "StringRegistry< Name >::Item", "classStringRegistry_1_1Item.html", null ],
    [ "BenchmarkState::Iterator", "classBenchmarkState_1_1Iterator.html", null ],
    [ "JsonArray", "classJsonArray.html", null ],
    [ "JsonObject", "classJsonObject.html", null ],
    [ "VariantLookup< T >::Key", "classVariantLookup_1_1Key.html", null ],
    [ "KlvFrame", "classKlvFrame.html", null ],
    [ "KlvReader", "classKlvReader.html", null ],
    [ "KlvWriter", "classKlvWriter.html", null ],
    [ "Line< T, N >", "classLine.html", null ],
    [ "List< T >", "classList.html", null ],
    [ "List< Attribute >", "classList.html", null ],
    [ "List< AudioGen * >", "classList.html", null ],
    [ "List< AudioGen::Config >", "classList.html", null ],
    [ "List< BenchmarkResult >", "classList.html", null ],
    [ "List< Buffer >", "classList.html", null ],
    [ "List< Char >", "classList.html", null ],
    [ "List< Cleanup >", "classList.html", null ],
    [ "List< CmdLineParser::Option >", "classList.html", null ],
    [ "List< CSCPipeline::Stage >", "classList.html", null ],
    [ "List< DebugMediaFile::FrameIndexEntry >", "classList.html", null ],
    [ "List< DecodedTimecode >", "classList.html", null ],
    [ "List< double >", "classList.html", null ],
    [ "List< float >", "classList.html", null ],
    [ "List< FourCC >", "classList.html", null ],
    [ "List< GridItem >", "classList.html", null ],
    [ "List< GroupEntry >", "classList.html", null ],
    [ "List< ID >", "classList.html", null ],
    [ "List< Info >", "classList.html", null ],
    [ "List< InspectorDiscontinuity >", "classList.html", null ],
    [ "List< int >", "classList.html", null ],
    [ "List< IoSource >", "classList.html", null ],
    [ "List< Item >", "classList.html", null ],
    [ "List< Layout * >", "classList.html", null ],
    [ "List< Membership >", "classList.html", null ],
    [ "List< ObjectBase * >", "classList.html", null ],
    [ "List< Params >", "classList.html", null ],
    [ "List< QueuedFrame >", "classList.html", null ],
    [ "List< QueueEntry >", "classList.html", null ],
    [ "List< SharedPtr >", "classList.html", null ],
    [ "List< SharedPtr< Buffer > >", "classList.html", null ],
    [ "List< SharedPtr< Frame > >", "classList.html", null ],
    [ "List< SignalMeta * >", "classList.html", null ],
    [ "List< SlotItem >", "classList.html", null ],
    [ "List< SlotMeta * >", "classList.html", null ],
    [ "List< std::thread >", "classList.html", null ],
    [ "List< String >", "classList.html", [
      [ "StringList", "classStringList.html", null ]
    ] ],
    [ "List< Tab >", "classList.html", null ],
    [ "List< TabPos >", "classList.html", null ],
    [ "List< Task >", "classList.html", null ],
    [ "List< TimerInfo >", "classList.html", null ],
    [ "List< Track >", "classList.html", null ],
    [ "List< TuiAction * >", "classList.html", null ],
    [ "List< TuiCell >", "classList.html", null ],
    [ "List< TuiMenu * >", "classList.html", null ],
    [ "List< Type >", "classList.html", null ],
    [ "List< uint8_t >", "classList.html", null ],
    [ "List< Variant >", "classList.html", [
      [ "VariantList", "classVariantList.html", null ]
    ] ],
    [ "List< Widget * >", "classList.html", null ],
    [ "Mutex::Locker", "classMutex_1_1Locker.html", null ],
    [ "Logger::LogEntry", "structLogger_1_1LogEntry.html", null ],
    [ "Logger::LogFormat", "structLogger_1_1LogFormat.html", null ],
    [ "Logger", "classLogger.html", null ],
    [ "LtcDecoder", "classLtcDecoder.html", null ],
    [ "LtcEncoder", "classLtcEncoder.html", null ],
    [ "MacAddress", "classMacAddress.html", null ],
    [ "Map< K, V >", "classMap.html", null ],
    [ "Map< int, int >", "classMap.html", null ],
    [ "Map< Pair, Accumulator >", "classMap.html", null ],
    [ "Map< size_t, Audio >", "classMap.html", null ],
    [ "Map< std::atomic< ObjectBase * > *, std::atomic< ObjectBase * > * >", "classMap.html", null ],
    [ "Map< String, CmdLineParser::Option >", "classMap.html", null ],
    [ "Map< String, double >", "classMap.html", null ],
    [ "Map< String, Params >", "classMap.html", null ],
    [ "Map< String, String >", "classMap.html", null ],
    [ "Map< uint32_t, CachedGlyph >", "classMap.html", null ],
    [ "Map< uint32_t, SDLWindow * >", "classMap.html", null ],
    [ "Map< uint64_t, ComposeEntry >", "classMap.html", null ],
    [ "Map< uint64_t, IndexedCompEntry >", "classMap.html", null ],
    [ "Map< uint64_t, IndexedScalarEntry >", "classMap.html", null ],
    [ "Map< uint64_t, ScalarEntry >", "classMap.html", null ],
    [ "Map< uint64_t, String >", "classMap.html", null ],
    [ "Map< uint64_t, Variant >", "classMap.html", null ],
    [ "Map< uint64_t, VariantSpec >", "classMap.html", null ],
    [ "Map< uintptr_t, Block >", "classMap.html", null ],
    [ "MasteringDisplay", "classMasteringDisplay.html", null ],
    [ "Matrix< T, W, H >", "classMatrix.html", null ],
    [ "Matrix3x3", "classMatrix3x3.html", null ],
    [ "MediaDesc", "classMediaDesc.html", null ],
    [ "MediaIOCommand", "classMediaIOCommand.html", [
      [ "MediaIOCommandClose", "classMediaIOCommandClose.html", null ],
      [ "MediaIOCommandOpen", "classMediaIOCommandOpen.html", null ],
      [ "MediaIOCommandParams", "classMediaIOCommandParams.html", null ],
      [ "MediaIOCommandRead", "classMediaIOCommandRead.html", null ],
      [ "MediaIOCommandSeek", "classMediaIOCommandSeek.html", null ],
      [ "MediaIOCommandStats", "classMediaIOCommandStats.html", null ],
      [ "MediaIOCommandWrite", "classMediaIOCommandWrite.html", null ]
    ] ],
    [ "MediaIODescription", "classMediaIODescription.html", null ],
    [ "MediaIOTask", "classMediaIOTask.html", [
      [ "MediaIOTask_AudioFile", "classMediaIOTask__AudioFile.html", null ],
      [ "MediaIOTask_Burn", "classMediaIOTask__Burn.html", null ],
      [ "MediaIOTask_CSC", "classMediaIOTask__CSC.html", null ],
      [ "MediaIOTask_DebugMedia", "classMediaIOTask__DebugMedia.html", null ],
      [ "MediaIOTask_FrameBridge", "classMediaIOTask__FrameBridge.html", null ],
      [ "MediaIOTask_FrameSync", "classMediaIOTask__FrameSync.html", null ],
      [ "MediaIOTask_ImageFile", "classMediaIOTask__ImageFile.html", null ],
      [ "MediaIOTask_Inspector", "classMediaIOTask__Inspector.html", null ],
      [ "MediaIOTask_QuickTime", "classMediaIOTask__QuickTime.html", null ],
      [ "MediaIOTask_RawBitstream", "classMediaIOTask__RawBitstream.html", null ],
      [ "MediaIOTask_Rtp", "classMediaIOTask__Rtp.html", null ],
      [ "MediaIOTask_SRC", "classMediaIOTask__SRC.html", null ],
      [ "MediaIOTask_TPG", "classMediaIOTask__TPG.html", null ],
      [ "MediaIOTask_VideoDecoder", "classMediaIOTask__VideoDecoder.html", null ],
      [ "MediaIOTask_VideoEncoder", "classMediaIOTask__VideoEncoder.html", null ],
      [ "SDLPlayerOldTask", "classSDLPlayerOldTask.html", null ],
      [ "SDLPlayerTask", "classSDLPlayerTask.html", null ]
    ] ],
    [ "MediaPacket", "classMediaPacket.html", null ],
    [ "MediaPipelineConfig", "classMediaPipelineConfig.html", null ],
    [ "MediaPipelinePlanner", "classMediaPipelinePlanner.html", null ],
    [ "MediaPipelineStats", "classMediaPipelineStats.html", null ],
    [ "MediaTimeStamp", "classMediaTimeStamp.html", null ],
    [ "MemAllocation", "structMemAllocation.html", null ],
    [ "MemPool", "classMemPool.html", null ],
    [ "MemSpace", "classMemSpace.html", null ],
    [ "ObjectBase::MetaInfo", "classObjectBase_1_1MetaInfo.html", null ],
    [ "MidiNote", "classMidiNote.html", null ],
    [ "MidiNoteNames", "classMidiNoteNames.html", null ],
    [ "Timecode::Mode", "classTimecode_1_1Mode.html", null ],
    [ "MusicalNote", "classMusicalNote.html", null ],
    [ "MusicalScale", "classMusicalScale.html", null ],
    [ "Mutex", "classMutex.html", null ],
    [ "H264Bitstream::NalUnit", "structH264Bitstream_1_1NalUnit.html", null ],
    [ "NetworkAddress", "classNetworkAddress.html", null ],
    [ "NoteSequenceParser", "classNoteSequenceParser.html", null ],
    [ "NumName", "classNumName.html", null ],
    [ "NumNameSeq", "classNumNameSeq.html", null ],
    [ "ObfuscatedString< N, Seed >", "classObfuscatedString.html", null ],
    [ "ObjectBase", "classObjectBase.html", [
      [ "AudioBlock", "classAudioBlock.html", null ],
      [ "DebugMediaFile", "classDebugMediaFile.html", null ],
      [ "FrameBridge", "classFrameBridge.html", null ],
      [ "IODevice", "classIODevice.html", [
        [ "AbstractSocket", "classAbstractSocket.html", [
          [ "RawSocket", "classRawSocket.html", null ],
          [ "TcpSocket", "classTcpSocket.html", null ],
          [ "UdpSocket", "classUdpSocket.html", [
            [ "PrioritySocket", "classPrioritySocket.html", null ]
          ] ]
        ] ],
        [ "BufferIODevice", "classBufferIODevice.html", null ],
        [ "BufferedIODevice", "classBufferedIODevice.html", [
          [ "File", "classFile.html", null ]
        ] ],
        [ "FileIODevice", "classFileIODevice.html", null ],
        [ "LocalSocket", "classLocalSocket.html", null ],
        [ "StreamStringIODevice", "classStreamStringIODevice.html", null ],
        [ "StringIODevice", "classStringIODevice.html", null ]
      ] ],
      [ "Layout", "classLayout.html", [
        [ "BoxLayout", "classBoxLayout.html", [
          [ "HBoxLayout", "classHBoxLayout.html", null ],
          [ "VBoxLayout", "classVBoxLayout.html", null ]
        ] ],
        [ "GridLayout", "classGridLayout.html", null ]
      ] ],
      [ "LocalServer", "classLocalServer.html", null ],
      [ "MediaIO", "classMediaIO.html", null ],
      [ "MediaPipeline", "classMediaPipeline.html", null ],
      [ "MulticastManager", "classMulticastManager.html", null ],
      [ "Process", "classProcess.html", null ],
      [ "RtpSession", "classRtpSession.html", null ],
      [ "TcpServer", "classTcpServer.html", null ],
      [ "Thread", "classThread.html", [
        [ "MulticastReceiver", "classMulticastReceiver.html", null ]
      ] ],
      [ "TuiAction", "classTuiAction.html", null ],
      [ "Widget", "classWidget.html", [
        [ "SDLVideoWidget", "classSDLVideoWidget.html", null ],
        [ "SDLWindow", "classSDLWindow.html", null ],
        [ "TuiWidget", "classTuiWidget.html", [
          [ "TuiButton", "classTuiButton.html", null ],
          [ "TuiCheckBox", "classTuiCheckBox.html", null ],
          [ "TuiFrame", "classTuiFrame.html", null ],
          [ "TuiLabel", "classTuiLabel.html", null ],
          [ "TuiLineEdit", "classTuiLineEdit.html", null ],
          [ "TuiListView", "classTuiListView.html", null ],
          [ "TuiMenu", "classTuiMenu.html", null ],
          [ "TuiMenuBar", "classTuiMenuBar.html", null ],
          [ "TuiProgressBar", "classTuiProgressBar.html", null ],
          [ "TuiScrollArea", "classTuiScrollArea.html", null ],
          [ "TuiSplitter", "classTuiSplitter.html", null ],
          [ "TuiStatusBar", "classTuiStatusBar.html", null ],
          [ "TuiTabWidget", "classTuiTabWidget.html", null ],
          [ "TuiTextArea", "classTuiTextArea.html", null ]
        ] ]
      ] ]
    ] ],
    [ "ObjectBasePtr< T >", "classObjectBasePtr.html", null ],
    [ "DebugMediaFile::OpenOptions", "structDebugMediaFile_1_1OpenOptions.html", null ],
    [ "MemSpace::Ops", "structMemSpace_1_1Ops.html", null ],
    [ "CmdLineParser::Option", "classCmdLineParser_1_1Option.html", null ],
    [ "FramePacer::PaceResult", "structFramePacer_1_1PaceResult.html", null ],
    [ "PacketTransport", "classPacketTransport.html", [
      [ "LoopbackTransport", "classLoopbackTransport.html", null ],
      [ "UdpSocketTransport", "classUdpSocketTransport.html", null ]
    ] ],
    [ "PaintEngine", "classPaintEngine.html", null ],
    [ "Pair< A, B >", "classPair.html", null ],
    [ "CRC< T >::Params", "structCRC_1_1Params.html", null ],
    [ "TuiInputParser::ParsedEvent", "structTuiInputParser_1_1ParsedEvent.html", null ],
    [ "VideoFormat::ParseOptions", "structVideoFormat_1_1ParseOptions.html", null ],
    [ "PeriodicCallback", "classPeriodicCallback.html", null ],
    [ "PIDController< ValueType, TimeType >", "classPIDController.html", null ],
    [ "PaintEngine::Pixel", "structPaintEngine_1_1Pixel.html", null ],
    [ "PixelDesc", "classPixelDesc.html", null ],
    [ "PixelFormat", "classPixelFormat.html", null ],
    [ "PixelFormat::PlaneDesc", "structPixelFormat_1_1PlaneDesc.html", null ],
    [ "Point< T, NumValues >", "classPoint.html", null ],
    [ "Point< int32_t, 2 >", "classPoint.html", null ],
    [ "Point< T, 2 >", "classPoint.html", null ],
    [ "Point< T, N >", "classPoint.html", null ],
    [ "MediaPipelinePlanner::Policy", "structMediaPipelinePlanner_1_1Policy.html", null ],
    [ "PriorityQueue< T, Compare >", "classPriorityQueue.html", null ],
    [ "Promise< T >", "classPromise.html", null ],
    [ "Promise< Error >", "classPromise.html", null ],
    [ "Promise< void >", "classPromise_3_01void_01_4.html", null ],
    [ "PromiseError", "structPromiseError.html", null ],
    [ "FrameSync::PullResult", "structFrameSync_1_1PullResult.html", null ],
    [ "Queue< T >", "classQueue.html", null ],
    [ "Queue< Command >", "classQueue.html", null ],
    [ "Queue< Error >", "classQueue.html", null ],
    [ "Queue< Item >", "classQueue.html", null ],
    [ "Queue< SharedPtr >", "classQueue.html", null ],
    [ "Queue< SharedPtr< Frame > >", "classQueue.html", null ],
    [ "QuickTime", "classQuickTime.html", null ],
    [ "Random", "classRandom.html", null ],
    [ "RateTracker", "classRateTracker.html", null ],
    [ "Rational< T >", "classRational.html", null ],
    [ "Rational< unsigned int >", "classRational.html", null ],
    [ "ReadWriteLock::ReadLocker", "classReadWriteLock_1_1ReadLocker.html", null ],
    [ "ReadWriteLock", "classReadWriteLock.html", null ],
    [ "Rect< T >", "classRect.html", null ],
    [ "Rect< int32_t >", "classRect.html", null ],
    [ "RefCount", "classRefCount.html", null ],
    [ "RegEx", "classRegEx.html", null ],
    [ "VariantLookup< T >::Registrar", "classVariantLookup_1_1Registrar.html", null ],
    [ "Signal< Args >::removeConstAndRef< T >", "structSignal_1_1removeConstAndRef.html", null ],
    [ "Slot< Args >::removeConstAndRef< T >", "structSlot_1_1removeConstAndRef.html", null ],
    [ "Resource", "classResource.html", null ],
    [ "MediaPipelineConfig::Route", "structMediaPipelineConfig_1_1Route.html", null ],
    [ "SdpMediaDescription::RtpMap", "structSdpMediaDescription_1_1RtpMap.html", null ],
    [ "RtpPayload", "classRtpPayload.html", [
      [ "RtpPayloadJpeg", "classRtpPayloadJpeg.html", null ],
      [ "RtpPayloadJpegXs", "classRtpPayloadJpegXs.html", null ],
      [ "RtpPayloadJson", "classRtpPayloadJson.html", null ],
      [ "RtpPayloadL16", "classRtpPayloadL16.html", null ],
      [ "RtpPayloadL24", "classRtpPayloadL24.html", null ],
      [ "RtpPayloadRawVideo", "classRtpPayloadRawVideo.html", null ]
    ] ],
    [ "QuickTime::Sample", "structQuickTime_1_1Sample.html", null ],
    [ "SDLAudioOutput", "classSDLAudioOutput.html", null ],
    [ "SDLEventPump", "classSDLEventPump.html", null ],
    [ "SdlSubsystem", "classSdlSubsystem.html", null ],
    [ "SdpMediaDescription", "classSdpMediaDescription.html", null ],
    [ "SdpSession", "classSdpSession.html", null ],
    [ "SelfPipe", "classSelfPipe.html", null ],
    [ "Set< T >", "classSet.html", null ],
    [ "Set< Block >", "classSet.html", null ],
    [ "SharedMemory", "classSharedMemory.html", null ],
    [ "SharedPtr< T, CopyOnWrite, ST >", "classSharedPtr.html", null ],
    [ "SharedPtr< AudioFile::Impl >", "classSharedPtr.html", null ],
    [ "SharedPtr< Benchmark >", "classSharedPtr.html", null ],
    [ "SharedPtr< Buffer >", "classSharedPtr.html", null ],
    [ "SharedPtr< Frame >", "classSharedPtr.html", null ],
    [ "SharedPtr< Image >", "classSharedPtr.html", null ],
    [ "SharedPtr< MediaPacket >", "classSharedPtr.html", null ],
    [ "SharedPtr< PaintEngine::Impl, false >", "classSharedPtr.html", null ],
    [ "SharedPtr< QuickTime::Impl >", "classSharedPtr.html", null ],
    [ "SharedPtr< StringData >", "classSharedPtr.html", null ],
    [ "SharedPtrProxy< T >", "classSharedPtrProxy.html", null ],
    [ "Signal< Args >", "classSignal.html", null ],
    [ "Signal< ObjectBase * >", "classSignal.html", null ],
    [ "SignalHandler", "classSignalHandler.html", null ],
    [ "ObjectBase::SignalMeta", "classObjectBase_1_1SignalMeta.html", null ],
    [ "Size2DTemplate< T >", "classSize2DTemplate.html", null ],
    [ "Size2DTemplate< int32_t >", "classSize2DTemplate.html", null ],
    [ "Size2DTemplate< uint32_t >", "classSize2DTemplate.html", null ],
    [ "Slot< Args >", "classSlot.html", null ],
    [ "ObjectBase::SlotMeta", "classObjectBase_1_1SlotMeta.html", null ],
    [ "MemSpace::Stats::Snapshot", "structMemSpace_1_1Stats_1_1Snapshot.html", null ],
    [ "SocketAddress", "classSocketAddress.html", null ],
    [ "Span< T >", "classSpan.html", null ],
    [ "Stack< T >", "classStack.html", null ],
    [ "CSCPipeline::Stage", "structCSCPipeline_1_1Stage.html", null ],
    [ "MediaPipelineConfig::Stage", "structMediaPipelineConfig_1_1Stage.html", null ],
    [ "MemPool::Stats", "structMemPool_1_1Stats.html", null ],
    [ "MemSpace::Stats", "structMemSpace_1_1Stats.html", null ],
    [ "SDLAudioClock::Stats", "structSDLAudioClock_1_1Stats.html", null ],
    [ "StatsAccumulator", "classStatsAccumulator.html", null ],
    [ "BenchmarkReporter::StepStats", "structBenchmarkReporter_1_1StepStats.html", null ],
    [ "Strand", "classStrand.html", null ],
    [ "StreamString", "classStreamString.html", null ],
    [ "String", "classString.html", null ],
    [ "StringData", "classStringData.html", [
      [ "StringLatin1Data", "classStringLatin1Data.html", null ],
      [ "StringLiteralData", "classStringLiteralData.html", null ],
      [ "StringUnicodeData", "classStringUnicodeData.html", null ],
      [ "StringUnicodeLiteralData", "classStringUnicodeLiteralData.html", null ]
    ] ],
    [ "VideoFormat::StringOptions", "structVideoFormat_1_1StringOptions.html", null ],
    [ "StringRegistry< Name >", "classStringRegistry.html", null ],
    [ "StringRegistry<\"Benchmark\">", "classStringRegistry.html", null ],
    [ "StructDatabase< KeyType, StructType >", "classStructDatabase.html", null ],
    [ "System", "classSystem.html", null ],
    [ "Terminal", "classTerminal.html", null ],
    [ "TextStream", "classTextStream.html", null ],
    [ "ThreadPool", "classThreadPool.html", null ],
    [ "Timecode", "classTimecode.html", null ],
    [ "TimecodeGenerator", "classTimecodeGenerator.html", null ],
    [ "TimeStamp", "classTimeStamp.html", null ],
    [ "promeki::ToStringFormatter", null, [
      [ "std::formatter< promeki::Point< T, NumValues > >", "structstd_1_1formatter_3_01promeki_1_1Point_3_01T_00_01NumValues_01_4_01_4.html", null ],
      [ "std::formatter< promeki::Rational< T > >", "structstd_1_1formatter_3_01promeki_1_1Rational_3_01T_01_4_01_4.html", null ],
      [ "std::formatter< promeki::Size2DTemplate< T > >", "structstd_1_1formatter_3_01promeki_1_1Size2DTemplate_3_01T_01_4_01_4.html", null ]
    ] ],
    [ "QuickTime::Track", "classQuickTime_1_1Track.html", null ],
    [ "std::true_type", null, [
      [ "IsSharedObject< T, std::void_t< decltype(&T::_promeki_refct)> >", "structIsSharedObject_3_01T_00_01std_1_1void__t_3_01decltype_07_6T_1_1__promeki__refct_08_4_01_4.html", null ],
      [ "detail::is_type_registry< AudioCodec >", "structdetail_1_1is__type__registry_3_01AudioCodec_01_4.html", null ],
      [ "detail::is_type_registry< ColorModel >", "structdetail_1_1is__type__registry_3_01ColorModel_01_4.html", null ],
      [ "detail::is_type_registry< MemSpace >", "structdetail_1_1is__type__registry_3_01MemSpace_01_4.html", null ],
      [ "detail::is_type_registry< PixelDesc >", "structdetail_1_1is__type__registry_3_01PixelDesc_01_4.html", null ],
      [ "detail::is_type_registry< PixelFormat >", "structdetail_1_1is__type__registry_3_01PixelFormat_01_4.html", null ],
      [ "detail::is_type_registry< VideoCodec >", "structdetail_1_1is__type__registry_3_01VideoCodec_01_4.html", null ]
    ] ],
    [ "TuiCell", "structTuiCell.html", null ],
    [ "TuiInputParser", "classTuiInputParser.html", null ],
    [ "TuiPainter", "classTuiPainter.html", null ],
    [ "TuiPalette", "classTuiPalette.html", null ],
    [ "TuiScreen", "classTuiScreen.html", null ],
    [ "TuiStyle", "classTuiStyle.html", null ],
    [ "TuiStyleState", "classTuiStyleState.html", null ],
    [ "TuiSubsystem", "classTuiSubsystem.html", null ],
    [ "Enum::Type", "classEnum_1_1Type.html", null ],
    [ "UMID", "classUMID.html", null ],
    [ "Units", "classUnits.html", null ],
    [ "UUID", "classUUID.html", null ],
    [ "VariantDatabase< Name >", "classVariantDatabase.html", null ],
    [ "VariantDatabase<\"Config\">", "classVariantDatabase.html", null ],
    [ "VariantDatabase<\"LibraryOptions\">", "classVariantDatabase.html", [
      [ "LibraryOptions", "classLibraryOptions.html", null ]
    ] ],
    [ "VariantDatabase<\"MediaConfig\">", "classVariantDatabase.html", [
      [ "MediaConfig", "classMediaConfig.html", null ]
    ] ],
    [ "VariantDatabase<\"MediaIOParams\">", "classVariantDatabase.html", null ],
    [ "VariantDatabase<\"MediaIOStats\">", "classVariantDatabase.html", [
      [ "MediaIOStats", "classMediaIOStats.html", null ]
    ] ],
    [ "VariantDatabase<\"Metadata\">", "classVariantDatabase.html", [
      [ "Metadata", "classMetadata.html", null ]
    ] ],
    [ "VariantDatabase<\"PipelineStats\">", "classVariantDatabase.html", [
      [ "PipelineStats", "classPipelineStats.html", null ]
    ] ],
    [ "detail::VariantEnd", "structdetail_1_1VariantEnd.html", null ],
    [ "VariantImpl< Types >", "classVariantImpl.html", null ],
    [ "VariantImpl< std::monostate, bool, uint8_t, int8_t, uint16_t, int16_t, uint32_t, int32_t, uint64_t, int64_t, float, double, String, DateTime, TimeStamp, MediaTimeStamp, Size2Du32, UUID, UMID, Timecode, Rational< int >, FrameRate, VideoFormat, StringList, Color, ColorModel, MemSpace, PixelFormat, PixelDesc, VideoCodec, AudioCodec, Enum, EnumList, MasteringDisplay, ContentLightLevel, detail::VariantEnd >", "classVariantImpl.html", [
      [ "Variant", "classVariant.html", null ]
    ] ],
    [ "VariantLookup< T >", "classVariantLookup.html", null ],
    [ "detail::VariantLookupSegment", "structdetail_1_1VariantLookupSegment.html", null ],
    [ "VariantQuery< T >", "classVariantQuery.html", null ],
    [ "detail::VariantQueryContext", "structdetail_1_1VariantQueryContext.html", null ],
    [ "VariantSpec", "classVariantSpec.html", null ],
    [ "VideoCodec", "classVideoCodec.html", null ],
    [ "VideoDecoder", "classVideoDecoder.html", [
      [ "JpegVideoDecoder", "classJpegVideoDecoder.html", null ],
      [ "JpegXsVideoDecoder", "classJpegXsVideoDecoder.html", null ]
    ] ],
    [ "VideoEncoder", "classVideoEncoder.html", [
      [ "JpegVideoEncoder", "classJpegVideoEncoder.html", null ],
      [ "JpegXsVideoEncoder", "classJpegXsVideoEncoder.html", null ]
    ] ],
    [ "VideoFormat", "classVideoFormat.html", null ],
    [ "VideoTestPattern", "classVideoTestPattern.html", null ],
    [ "WaitCondition", "classWaitCondition.html", null ],
    [ "ReadWriteLock::WriteLocker", "classReadWriteLock_1_1WriteLocker.html", null ],
    [ "XYZColor", "classXYZColor.html", null ]
];